CREATE TABLE BOARD(
	BOARD_NUM NUMBER,
	BOARD_NAME VARCHAR2(30),
	BOARD_PASS VARCHAR2(30),
	BOARD_SUBJECT VARCHAR2(300),
	BOARD_CONTENT VARCHAR2(4000),
	BOARD_FILE VARCHAR2(50),
	BOARD_RE_REF NUMBER,
	BOARD_RE_LEV NUMBER,
	BOARD_RE_SEQ NUMBER,
	BOARD_READCOUNT NUMBER,
	BOARD_DATE DATE,
	PRIMARY KEY(BOARD_NUM))
	
	SELECT * 
	FROM (SELECT ROWNUM AS "PAGE", BOARD_NUM, BOARD_NAME, BOARD_SUBJECT, BOARD_CONTENT, BOARD_FILE, BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_READCOUNT, BOARD_DATE  
			FROM (SELECT BOARD_NUM, BOARD_NAME, BOARD_SUBJECT, BOARD_CONTENT, BOARD_FILE, BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_READCOUNT, BOARD_DATE
					FROM BOARD
					ORDER BY BOARD_NUM DESC)
			)
	WHERE PAGE >= 1 AND PAGE < 11
	
	SELECT * 
				FROM (SELECT ROWNUM AS "PAGE", BOARD_NUM, BOARD_NAME, BOARD_SUBJECT, BOARD_CONTENT, BOARD_FILE, BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_READCOUNT, BOARD_DATE 
				FROM (SELECT BOARD_NUM, BOARD_NAME, BOARD_SUBJECT, BOARD_CONTENT, BOARD_FILE, BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_READCOUNT, BOARD_DATE
				FROM BOARD
				ORDER BY BOARD_NUM DESC)
				)
				WHERE PAGE >= 1 AND PAGE < 11)